### PR TITLE
Added testing for activities.json

### PR DESCRIPTION
**Pull request by Perlkonig**
1) I created a JSON schema for the activity entry. This makes testing for well-formedness *much* easier. I tried to use `multipleOf` to constrain the precision of `accessibility` and `price`, but JavaScript number precision made that infeasible. 

2) I then created the following three new tests:
    * Each line should be valid JSON (`JSON.parse()` succeeds)
    * Each line should match the schema (using `ajv` package)
    * Each key should be unique (simple accumulation of keys and comparing)

    I would have put these in a separate file, but the one you have is already called `activities`, so I just lumped them in. Refactor as you desire. This also included adding `ajv` to the package file as a dev dependency.

3) Finally, I corrected the `activities.json` file in light of the test results. This involved changing two `key` values. This may require flushing the database before updating to avoid duplication.

None of these changes should conflict with others I've submitted recently. Again, I am no expert. Coding is a hobby, and JavaScript is my least favourite language. Let me know if I've done something wrong or if you'd like changes made.

### CODE REVIEW

**Comment by drewthoennes** [comment]
I really really like this and this is definitely something I wish this project had sooner!

These integration tests are solely for testing the integrity of the API endpoints, so can you move these tests and activity-schema-v1.json to test/backend/db?

**Comment by Perlkonig** [comment]
Will do.

**Comment by Perlkonig** [comment]
Sorry. I rebased to run the tests on the updated activities file, and now screwed up the whole branch. Reverting, and will update the activities file after the tests are merged.

**Comment by drewthoennes** [comment]
Apologies on the belated merge, I just finished my finals and my semester. Looks great to me!

**Pull request merged**
